In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('titanic_dataset.csv')

In [ ]:
# How big is data

df.shape

(418, 12)

In [ ]:
# How does the data look like?
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df.sample(5)#it will give 5 random rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
111,1003,1,3,"Shine, Miss. Ellen Natalia",female,NaN,0,0,330968,7.7792,NaN,Q
276,1168,0,2,"Parker, Mr. Clifford Richard",male,28.0,0,0,SC 14888,10.5000,NaN,S
302,1194,0,2,"Phillips, Mr. Escott Robert",male,43.0,0,1,S.O./P.P. 2,21.0000,NaN,S
265,1157,0,3,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,NaN,S
165,1057,1,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26.0,1,1,315153,22.0250,NaN,S

In [ ]:
# what is the data type of cols?

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [ ]:
# Are there any missing values

df.isnull().sum()#it will give the no of missing values

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
# How does the data looks mathematically?

df.describe()# it will give mathematical summary of the data
# it will give insights only on numerical coloumns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [ ]:
# Are there duplicate values?

df.duplicated().sum()

np.int64(0)

In [ ]:
# How is the correlation between cols?
# df.corr()// not working because df contains strings
df.describe().corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.464876,-0.461246,-0.351457,-0.459851,-0.459767,-0.011424
Survived,-0.464876,1.000000,0.999985,0.979671,0.999864,0.999812,0.555351
Pclass,-0.461246,0.999985,1.000000,0.980197,0.999864,0.999811,0.556141
Age,-0.351457,0.979671,0.980197,1.000000,0.982338,0.982603,0.688882
SibSp,-0.459851,0.999864,0.999864,0.982338,1.000000,0.999993,0.568942
Parch,-0.459767,0.999812,0.999811,0.982603,0.999993,1.000000,0.571173
Fare,-0.011424,0.555351,0.556141,0.688882,0.568942,0.571173,1.000000

In [ ]:
df.describe().corr()['Survived']

PassengerId   -0.464876
Survived       1.000000
Pclass         0.999985
Age            0.979671
SibSp          0.999864
Parch          0.999812
Fare           0.555351
Name: Survived, dtype: float64